/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Администратор' at '29.08.16 23:32' with Gradle 2.14.1
 *
 * @author Администратор, @date 29.08.16 23:32
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
